services:
  datagen:
    image: alzearly:v1
    working_dir: /workspace
    command: ["python", "run_datagen.py", "--config", "config/data_gen.yaml"]
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    restart: "no"

  training:
    image: alzearly:v1
    working_dir: /workspace
    command: ["python", "run_training.py", "--config", "config/model.yaml"]
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
      - WANDB_API_KEY=${WANDB_API_KEY:-}
    restart: "no"

  serve:
    image: alzearly:v1
    network_mode: "host"     # Linux only; fails if host:8001 is busy
    working_dir: /workspace
    command: ["python", "run_serve.py", "--host", "0.0.0.0", "--port", "8001"]
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    restart: unless-stopped
