services:
  # Data generation service
  datagen:
    build:
      context: .
      dockerfile: Dockerfile.datagen
    container_name: alzearly-datagen
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - TQDM_DISABLE=1
      - POLARS_NUM_THREADS=1
      - POLARS_STREAMING_COLLECT=0
      - POLARS_FORCE_OPTIMIZED=1
      - POLARS_USE_STREAMING=0
    command: ["python", "run_datagen.py"]
    profiles:
      - datagen

  # Training service - handles training and experiment tracking
  training:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: alzearly-train
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - TQDM_DISABLE=1
      - POLARS_NUM_THREADS=1
      - POLARS_STREAMING_COLLECT=0
      - POLARS_FORCE_OPTIMIZED=1
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - PYTHONPATH=/workspace
    command: ["python", "run_training.py", "--config", "config/model.yaml"]
    profiles:
      - training

  # Serving service - FastAPI development server
  serve:
    build:
      context: .
      dockerfile: Dockerfile.serve
    container_name: alzearly-serve
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - TQDM_DISABLE=1
      - POLARS_NUM_THREADS=1
      - POLARS_STREAMING_COLLECT=0
      - POLARS_FORCE_OPTIMIZED=1
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: ["python", "run_serve.py", "--port", "8001", "--host", "0.0.0.0"]
    profiles:
      - serve

  # Complete pipeline (training + serving)
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: alzearly-pipeline
    volumes:
      - .:/workspace
      - ../Data/alzearly:/Data
    environment:
      - PYTHONUNBUFFERED=1
      - TQDM_DISABLE=1
      - POLARS_NUM_THREADS=1
      - POLARS_STREAMING_COLLECT=0
      - POLARS_FORCE_OPTIMIZED=1
      - WANDB_API_KEY=${WANDB_API_KEY:-}
      - PYTHONPATH=/workspace
    command: ["python", "run_training.py", "--config", "config/model.yaml"]
    profiles:
      - pipeline

networks:
  default:
    name: alzearly-network
