# Data Generation Configuration
# Synthetic patient-year data generation for Alzheimer's prediction

# Dataset size and structure
dataset:
  # Number of patients to generate (will be multiplied by years)
  n_patients: 3000
  # Years to generate data for
  years: [2021, 2022, 2023, 2024]
  # Target total rows (overrides n_patients if specified)
  target_rows: null
  
# Target variable configuration
target:
  # Alzheimer's positive diagnosis rate (5-10% recommended)
  positive_rate: 0.08
  # Target variable column name
  column_name: "alzheimers_diagnosis"

# Processing configuration
processing:
  # Rows per chunk for memory efficiency
  rows_per_chunk: 3000
  # Random seed for reproducibility
  seed: 42

# Output configuration
output:
  # Output directory for raw data
  directory: "/Data/raw"
  # File format (parquet recommended)
  format: "parquet"
  # Partitioning strategy
  partitioning: "year"

# Clinical feature ranges (for realistic data generation)
clinical_ranges:
  age:
    min: 18
    max: 85
  bmi:
    min: 16.0
    max: 50.0
  systolic_bp:
    min: 70
    max: 220
  diastolic_bp:
    min: 40
    max: 130
  heart_rate:
    min: 50
    max: 120
  temperature:
    min: 95.0
    max: 103.0
  glucose:
    min: 50
    max: 300
  cholesterol_total:
    min: 100
    max: 500
  hdl:
    min: 20
    max: 100
  ldl:
    min: 30
    max: 250
  triglycerides:
    min: 30
    max: 600
  creatinine:
    min: 0.3
    max: 3.0
  hemoglobin:
    min: 8
    max: 22
  white_blood_cells:
    min: 2
    max: 20
  platelets:
    min: 50
    max: 600

# Alzheimer's risk factor weights
risk_factors:
  age_65_plus: 0.4
  age_75_plus: 0.6
  age_85_plus: 0.8
  low_education: 0.3
  obesity: 0.2
  hypertension: 0.25
  diabetes: 0.3
  high_cholesterol: 0.2
  female_gender: 0.1
