# Model Training Configuration
# Configuration for Alzheimer's prediction model training

# Data configuration
data:
  # Input directory for featurized data
  input_dir: "/Data/featurized"
  # Target variable column name
  target_column: "alzheimers_diagnosis"
  # Columns to exclude from features
  exclude_columns: ["patient_id", "year"]

# Split configuration
splits:
  # Test set size (fraction of total data)
  test_size: 0.2
  # Validation set size (fraction of training data)
  val_size: 0.2
  # Random seed for reproducibility
  random_state: 42
  # Whether to stratify splits
  stratify: true

# Feature selection
feature_selection:
  # Maximum number of features to keep
  max_features: 150
  # Variance threshold for feature filtering
  variance_threshold: 0.01

# Class imbalance handling
class_imbalance:
  # Method to handle class imbalance
  # Options: "class_weight", "smote", "none"
  method: "class_weight"

# Model configuration
models:
  # List of models to train
  # Options: ["logistic_regression", "xgboost"]
  types: ["logistic_regression", "xgboost"]

# XGBoost parameters
xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  random_state: 42
  eval_metric: "logloss"

# Logistic Regression parameters
logistic_regression:
  random_state: 42
  max_iter: 1000

# Hyperparameter tuning
hyperparameter_tuning:
  # Whether to enable hyperparameter tuning
  enabled: false
  # Number of trials for Optuna
  n_trials: 50
  # Timeout for tuning (seconds)
  timeout: 300

# Output configuration
output:
  # Output directory for models
  directory: "models"
  # Whether to save metadata
  save_metadata: true
  # Whether to log artifacts
  log_artifacts: true

# Experiment tracking
experiment_tracking:
  # Whether to enable experiment tracking
  enabled: true
  # Tracking backend (wandb, mlflow, none)
  backend: "wandb"
  # Project name for tracking
  project_name: "alzheimers_prediction"
